{
  config,
  lib,
  pkgs,
  inputs,
  host,
  ...
}:
let
  inherit (lib) mkEnableOption mkIf;
in
{
  imports = [
    ./hyprlock.nix
  ];

  options.features.wm.hyprland.enable = mkEnableOption "Enable Hyprland window manager";

  config = mkIf config.features.wm.hyprland.enable {
    # Enable Hyprland
    wayland.windowManager.hyprland = {
      enable = true;
      xwayland.enable = true;
      systemd.enable = true;

      settings = lib.mkMerge [
        (import ./env.nix { inherit host; })
        (import ./general.nix { inherit host; })
        (import ./keybinds.nix { inherit host; })
        (import ./rules.nix { inherit host; })
        (import ./exec.nix { inherit host; })
      ];

      extraConfig = ''
        # Source monitor and workspace configs generated by nwg-displays
        source = ~/.config/hypr/monitors.conf
        source = ~/.config/hypr/workspaces.conf
      '';
    };

    xdg.portal = {
      enable = true;

      extraPortals = with pkgs; [
        xdg-desktop-portal-gtk
      ];

      config = {
        common.default = "*";
        hyprland.default = [
          "hyprland"
          "gtk"
        ];
      };
    };

    features.application = {
      rofi.enable = true;
      waybar.enable = true;
      wlogout.enable = true;
      swaync.enable = true;
    };

    # Essential Hyprland packages
    home.packages = with pkgs; [
      # Wayland essentials
      wayland
      wayland-protocols
      wayland-utils

      # Hyprland ecosystem
      nwg-displays

      # Wallpaper
      swww

      # Screenshot
      grim
      slurp
      grimblast

      # Media control
      playerctl

      # Audio control
      wireplumber
      pavucontrol

      # Brightness control
      brightnessctl

      # Clipboard manager (optional)
      wl-clipboard
      cliphist
    ];
  };
}
