{
  config,
  lib,
  pkgs,
  inputs,
  ...
}:
let
  inherit (lib) mkEnableOption mkIf;
in
{
  imports = [
    ./hyprlock.nix
  ];

  options.features.wm.hyprland.enable = mkEnableOption "Enable Hyprland window manager";

  config = mkIf config.features.wm.hyprland.enable {
    # Enable Hyprland
    wayland.windowManager.hyprland = {
      enable = true;
      xwayland.enable = true;
      systemd.enable = true;

      # Enable plugins from the hyprland-plugins flake
      # Available plugins: hyprscrolling, hyprtrails, hyprwinwrap, hyprbars, hyprexpo, hyprgrass
      plugins = [
        inputs.hyprland-plugins.packages.${pkgs.stdenv.hostPlatform.system}.hyprscrolling
        # inputs.hyprland-plugins.packages.${pkgs.stdenv.hostPlatform.system}.hyprtrails
        # inputs.hyprland-plugins.packages.${pkgs.stdenv.hostPlatform.system}.hyprwinwrap
        # inputs.hyprland-plugins.packages.${pkgs.stdenv.hostPlatform.system}.hyprbars
        # inputs.hyprland-plugins.packages.${pkgs.stdenv.hostPlatform.system}.hyprexpo
        # inputs.hyprland-plugins.packages.${pkgs.stdenv.hostPlatform.system}.hyprgrass
      ];

      settings = lib.mkMerge [
        (import ./env.nix)
        (import ./general.nix)
        (import ./keybinds.nix)
        (import ./rules.nix)
        (import ./exec.nix)
      ];

      extraConfig = ''
        # Source monitor and workspace configs generated by nwg-displays
        source = ~/.config/hypr/monitors.conf
        source = ~/.config/hypr/workspaces.conf
      '';
    };

    xdg.portal = {
      enable = true;

      extraPortals = with pkgs; [
        xdg-desktop-portal-gtk
      ];

      config = {
        common.default = "*";
        hyprland.default = [
          "hyprland"
          "gtk"
        ];
      };
    };

    features.application = {
      rofi.enable = true;
      waybar.enable = true;
      wlogout.enable = true;
      swaync.enable = true;
    };

    # Essential Hyprland packages
    home.packages = with pkgs; [
      # Wayland essentials
      wayland
      wayland-protocols
      wayland-utils

      # Hyprland ecosystem
      nwg-displays

      # Wallpaper
      swww

      # Screenshot
      grim
      slurp
      grimblast

      # Media control
      playerctl

      # Audio control
      wireplumber
      pavucontrol

      # Brightness control
      brightnessctl

      # Auto-mounting
      udiskie

      # Image viewer
      nsxiv

      # Clipboard manager (optional)
      wl-clipboard
      cliphist
    ];

    # Services
    services = {
      # Auto-mounting
      udiskie = {
        enable = true;
        automount = true;
        notify = true;
        tray = "auto";
      };
    };
  };
}
